spring.application.name=JPA-Spring-Security
spring.datasource.url=jdbc:sqlserver://localhost:3306//SQLEXPRESS:1443;databaseName=student_ms2;encrypt=true;trustServerCertificate=true;
spring.datasource.username=root
spring.datasource.password=your_password

#  DEBUG
#logging.level.org.springframework.jdbc.core=TRACE


 spring.jpa.hibernate.ddl-auto=update
 
spring.jpa.show-sql=true
